# Generated by Django 5.1.2 on 2024-11-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_favorite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
